# File: .github/workflows/trigger.yml
# Branch: main

name: Trigger Reusable Workflow from testing_workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Optional: manual trigger for testing

permissions:
  actions: write
  contents: read

jobs:
  call-test-workflow:
    uses: sumaparamp/course-gh-actions/.github/workflows/test_wf.yml@testing_workflow
    with:
      branch: testing_workflow
