name: Trigger Testing Workflow

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_run:
    workflows: ["testing_workflow"]
    types:
      - completed

jobs:
  run-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v4
        with:
          ref: testing_workflow

      - name: Run script
        run: |
          echo "Running code from feature branch"